"use client";

import { useSprintReports } from "@/lib/hooks/use-reports";

export function SprintReportCard({ projectId }: { projectId: string }) {
  const { data, isLoading } = useSprintReports(projectId);

  if (isLoading) return <div className="p-4 bg-white border rounded-lg">Loading reports...</div>;
  if (!data || data.items.length === 0)
    return <div className="p-4 bg-white border rounded-lg text-gray-400">No sprint reports yet</div>;

  return (
    <div className="p-4 bg-white border rounded-lg">
      <h3 className="text-sm font-semibold mb-3">Sprint Reports</h3>
      <div className="space-y-2">
        {data.items.map((report) => (
          <div key={report.id} className="p-3 bg-gray-50 rounded border">
            <div className="flex items-center justify-between">
              <span className="font-medium text-sm">Sprint Report</span>
              <span className="text-xs text-gray-500">
                {new Date(report.generatedAt).toLocaleDateString()}
              </span>
            </div>
            <p className="text-xs text-gray-500 mt-1">
              Generated by: {report.generatedBy}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
